#1) Create a 3*3 NumPy array between 1 and 100. Then interchange its rows and columns.

Solution:

In [ ]:
import numpy as np
# Create a 3*3 array with random integers between 1 and 100
arr = np.random.randint(1,100, size=(3,3))
arr

array([[41, 45, 29],
       [29, 27, 88],
       [44, 65, 31]])

In [ ]:
# for interchanging rows and columns using transpose() method;
arr1 = arr.T
arr1

array([[41, 29, 44],
       [45, 27, 65],
       [29, 88, 31]])

#2) Generate a 1D NumPy array with 10 elements. Reshape it into 2 * 5 array, and then into 5 * 2 array.

Solution:

In [ ]:
arr = np.arange(10) # Create a 1D NumPy array with 10 elements
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = arr.reshape(2,5) # Reshape array into 2*5 array
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr2 = arr.reshape(5,2) # Reshape array into 5*2 array
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#3)  Create a 4 * 4 NumPy  array with random float values. Add a border of zeroes around it, resulting into 6 * 6 array.

Solution:

In [ ]:
arr = np.random.rand(4,4)
arr

array([[0.40736269, 0.32887734, 0.18725023, 0.82648252],
       [0.79321783, 0.20245337, 0.61841129, 0.58215581],
       [0.1762788 , 0.4041765 , 0.52456816, 0.91604374],
       [0.53089633, 0.15610944, 0.02395427, 0.34892001]])

In [ ]:
# Add a border of zeroes using np.pad() function;
arr1 = np.pad(arr, pad_width =1, mode= 'constant', constant_values= 0)
print(arr1)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.40736269 0.32887734 0.18725023 0.82648252 0.        ]
 [0.         0.79321783 0.20245337 0.61841129 0.58215581 0.        ]
 [0.         0.1762788  0.4041765  0.52456816 0.91604374 0.        ]
 [0.         0.53089633 0.15610944 0.02395427 0.34892001 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#4) Using NumPy create a array of integers from 10 to 60 with a step of 5.

Solution:  



In [ ]:
arr = np.arange(10,60,5) # Create an array of integers from 10 and 60 with a step of 5.
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

# 5) Create a array of strings ['python', 'numpy', 'pandas']. Apply different transformation (uppercase, lowercase and titlecase etc.) to each element.

Solution:

In [ ]:
arr = np.array(['Python', 'NumPy', 'Pandas']) # Create a array of strings
arr

array(['Python', 'NumPy', 'Pandas'], dtype='<U6')

In [ ]:
# uppercase transformation;
arr1= np.char.upper(arr)
arr1

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
# Lowercase transformation;
arr2 = np.char.lower(arr)
arr2

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
# Titlecase transformation;
arr3 = np.char.title(arr)
arr3

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

#6) Generate a array of words. Insert a space between each character of every word in the array.

Solution:

In [ ]:
words = np.array(['Aadhyavi', 'is', 'a', 'data', 'science', 'student'])
spaced_words = np.char.join(' ', words)
spaced_words

array(['A a d h y a v i', 'i s', 'a', 'd a t a', 's c i e n c e',
       's t u d e n t'], dtype='<U15')

# 7) Create two 2D arrays and perform element wise addition, multiplication, substraction and division.

Solution:

In [ ]:
arr1 = np.array([[13,24,36,45,54,61]])
arr2 = np.array([[9,14,25,42,63,52]])

arr_addition = arr1 + arr2   # addition of two arrays
print(f"Addition of two values are: {arr_addition}")
arr_multiplication = arr1 * arr2   # multiplication of two arrays
print(f" Multiplication of two values is: {arr_multiplication}")
arr_substraction = arr1 - arr2   # substraction of two arrays
print(f"Substraction of two values is: {arr_substraction}")
arr_division = arr1 / arr2   # division of two arrays
print(f"Division of two values is: {arr_division}")

Addition of two values are: [[ 22  38  61  87 117 113]]
 Multiplication of two values is: [[ 117  336  900 1890 3402 3172]]
Substraction of two values is: [[ 4 10 11  3 -9  9]]
Division of two values is: [[1.44444444 1.71428571 1.44       1.07142857 0.85714286 1.17307692]]


#8) Use NumPy to create 5 * 5 indentity matrix, then extract its diagonal elements.

Solution:

In [ ]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#9) Generate a NumPy array of 100 random integers between 1 and 1000.Find and display all the prime numbers in this array.

Solution:

In [ ]:
arr = np.random.randint(1,1000, size=100)
arr

array([579, 898, 364, 294, 638, 820, 943,  62,  59, 481, 217, 657,  89,
       821, 686, 976, 726, 684, 293, 415, 977,  10, 720, 252, 271, 734,
       734, 463, 201, 696, 768, 631, 757, 785, 397, 771, 713, 916, 453,
       809, 794,  58, 785, 132, 597, 892, 931, 490,  24, 647, 757, 981,
       825, 538, 716, 887,  25, 410, 219, 216, 764, 878, 613, 105, 654,
       452, 136, 717, 816, 680,  46, 379, 220, 473, 975, 491, 353, 396,
       253,  17,  53, 747, 403,  35, 133,  52, 996, 544,  96, 814, 346,
       542, 207, 971, 758, 108, 789, 780, 423, 977])

In [ ]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) +1):
      if num % i == 0:
        return False
    return True


prime_numbers = [num for num in arr if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [59, 89, 821, 293, 977, 271, 463, 631, 757, 397, 809, 647, 757, 887, 613, 379, 491, 353, 17, 53, 971, 977]


# 10) Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly average.

Solution:

In [ ]:
daily_temp = np.random.uniform(15,35, size = 30)
daily_temp

array([30.03511285, 25.85781003, 32.59012649, 32.84205503, 19.03633722,
       25.90552648, 18.59107683, 24.39312467, 32.51156971, 22.16366191,
       26.03687895, 19.17344835, 32.1366368 , 33.23808087, 27.31108114,
       23.29578137, 21.38794994, 26.67927016, 16.34512244, 34.90471209,
       27.54982591, 22.5579823 , 21.3630396 , 34.70825967, 30.20819691,
       25.06985898, 21.27024515, 15.9223654 , 17.33237409, 26.46761356])

In [ ]:
# Calculate and display the weekly average;

week_1 = daily_temp[:7]
week_2 = daily_temp[7:14]
week_3 = daily_temp[14:21]
week_4 = daily_temp[21:]

week_1_avg = np.mean(week_1)
week_2_avg = np.mean(week_2)
week_3_avg = np.mean(week_3)
week_4_avg = np.mean(week_4)

print(f"Week 1 average temperature: {week_1_avg:.2f} degrees")
print(f"Week 2 average temperature: {week_2_avg:.2f} degrees")
print(f"Week 3 average temperature: {week_3_avg:.2f} degrees")
print(f"Week 4 average temperature: {week_4_avg:.2f} degrees")

Week 1 average temperature: 26.41 degrees
Week 2 average temperature: 27.09 degrees
Week 3 average temperature: 25.35 degrees
Week 4 average temperature: 23.88 degrees
